name: CI

on:
  pull_request:
  push:
    branches: [ master, develop ]

permissions:
  contents: read
  actions: read

jobs:
  run:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        php:
          - '8.1'
          - '8.2'
          - '8.3'
          - '8.4'
        coverage: [ 'none' ]
        symfony-versions:
          - '5.4.*'
          - '6.0.*'
          - '6.1.*'
          - '6.2.*'
          - '7.0.*'
        exclude:
          - php: '8.1'
            symfony-versions: '7.0.*'
        include:
          - description: 'Minimal PHP 8.1'
            php: '8.1'
            coverage: 'none'
            symfony-versions: 'none'
          - description: 'Minimal PHP 8.2'
            php: '8.2'
            coverage: 'none'
            symfony-versions: 'none'
          - description: 'Log Code Coverage'
            php: '8.2'
            coverage: 'xdebug'
            symfony-versions: 'none'
          - description: 'Minimal PHP 8.3'
            php: '8.3'
            coverage: 'none'
            symfony-versions: 'none'
          - description: 'Minimal PHP 8.4'
            php: '8.4'
            coverage: 'none'
            symfony-versions: 'none'

    name: PHP ${{ matrix.php }} Symfony ${{ matrix.symfony-versions }} ${{ matrix.description }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php }}
          coverage: ${{ matrix.coverage }}

      - name: Add PHPUnit matcher
        run: echo "::add-matcher::${{ runner.tool_cache }}/phpunit.json"

      - name: Update Symfony version
        if: matrix.symfony-versions != 'none'
        run: |
          composer require symfony/console:${{ matrix.symfony-versions }} --no-update --no-scripts
          composer require symfony/dotenv:${{ matrix.symfony-versions }} --no-update --no-scripts
          composer require symfony/messenger:${{ matrix.symfony-versions }} --no-update --no-scripts
          
          composer require --dev symfony/yaml:${{ matrix.symfony-versions }} --no-update --no-scripts
          composer require --dev symfony/phpunit-bridge:${{ matrix.symfony-versions }} --no-update --no-scripts

      - name: Install dependencies
        run: |
          if [ "${{ matrix.symfony-versions }}" != "none" ]; then
            composer update --no-progress --no-interaction --prefer-dist --optimize-autoloader
          else
            composer install --no-progress --no-interaction --prefer-dist --optimize-autoloader
          fi

      - name: Run PHPUnit tests
        run: composer phpunit
        if: matrix.coverage == 'none'

      - name: PHPUnit tests and Log Code coverage
        run: vendor/bin/simple-phpunit --coverage-clover=coverage.xml
        working-directory: ${{ github.workspace }}
        env:
          COMPOSER: ${{ github.workspace }}/composer.json
        if: matrix.coverage == 'xdebug'

      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v4
        if: matrix.coverage == 'xdebug'
        with:
          file: './coverage.xml'
          fail_ci_if_error: false
          token: ${{ secrets.CODECOV_TOKEN }}
