name: CI

on:
    pull_request:
    push:
        branches: [ master, develop ]

jobs:
    run:
        runs-on: ubuntu-18.04
        strategy:
            fail-fast: false
            matrix:
                php:
                    - '7.4'
                    - '8.0'

        name: PHP ${{ matrix.php }} ${{ matrix.description }}
        steps:
            - name: Checkout
              uses: actions/checkout@v2

            - uses: actions/cache@v2
              with:
                  path: ~/.composer/cache/files
                  key: ${{ matrix.php }}

            - name: Setup PHP
              uses: shivammathur/setup-php@v2
              with:
                  php-version: ${{ matrix.php }}
                  coverage: none

            - name: Install dependencies
              run: composer install

            - name: Run PHPUnit tests
              run: vendor/bin/simple-phpunit
