name: gitleaks

on: [push, pull_request]

jobs:
    gitleaks:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout
              uses: actions/checkout@v1

            - name: Run gitleaks
              uses: zricethezav/gitleaks-action@master
              with:
                  config-path: security/.gitleaks.toml
